a = eval(input())
b = eval(input())
c = eval(input())
d = eval(input())
print('|%7.2f %7.2f|' % (a, b))
print('|%7.2f %7.2f|' % (c, d))
print('|%-7.2f %-7.2f|' % (a, b))
print('|%-7.2f %-7.2f|' % (c, d))
